<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.a5b84.cliligrane</groupId>
    <artifactId>cliligrane-parent</artifactId>
    <version>1.0.0</version>
    <modules>
        <module>cliligrane</module>
        <module>common-library</module>
        <module>pdf-generator</module>
    </modules>
    <packaging>pom</packaging>

    <properties>
        <revision>3.5.12</revision>
        <java.version>21</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <assertj.version>3.27.7</assertj.version>
        <imageio.version>3.12.0</imageio.version>
        <jackson-bom.version>2.21.4</jackson-bom.version>
        <jhlabs-filters.version>2.0.235-1</jhlabs-filters.version>
        <jna.version>5.18.1</jna.version>
        <jspecify.version>1.0.0</jspecify.version>
        <junit.version>5.12.2</junit.version>
        <logback.version>1.5.36</logback.version>
        <lombok.version>1.18.34</lombok.version>
        <maven-assembly-plugin.version>3.7.1</maven-assembly-plugin.version>
        <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
        <pdfbox.version>3.0.6</pdfbox.version>
        <tika.version>3.3.0</tika.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.a5b84.cliligrane</groupId>
                <artifactId>common-library</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.a5b84.cliligrane</groupId>
                <artifactId>pdf-generator</artifactId>
                <version>${revision}</version>
            </dependency>

            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>${jackson-bom.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.pdfbox</groupId>
                <artifactId>pdfbox</artifactId>
                <version>${pdfbox.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.pdfbox</groupId>
                <artifactId>pdfbox-tools</artifactId>
                <version>${pdfbox.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.pdfbox</groupId>
                <artifactId>jbig2-imageio</artifactId>
                <version>${jbig2-imageio.version}</version>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>${assertj.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.jspecify</groupId>
                <artifactId>jspecify</artifactId>
                <version>${jspecify.version}</version>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
                <optional>true</optional>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>${maven-assembly-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
